### ISSUE TITLE
Theme und Design Basic

### ISSUE THREAD

**Issue by jvoigt** [bringbackourneighbours/bringbackourneighbours#11]
Damit wir alles entsprechend unsers Wünsch stylen können, insb auch für den druck und die sehr unterschiedlichen schriftarten (RTL/LTR) wäre es gut zwischen globalen themes wechseln zu können... und dann brauchen wir componenten für alles.

Hier soll de darum gehen ein paar basic componenten anzulegen damit diese schon mal gestylt werden können. das wären dann vor allem die Markdown elemente

**Comment by ponychicken** [comment]
I am happy with it for now. 
I guess some things can be cleaned up more. 
Astro seems to have some problem with nested styles. They are not applied correctly and I had to move them to base.css

**Comment by ponychicken** [comment]
Continuing in #20
