### ISSUE TITLE
Entscheidung für Hosting treffen

### ISSUE THREAD

**Issue by jvoigt** [bringbackourneighbours/bringbackourneighbours#39]
Voraussetzung:
- eine Entscheidung zugunsten einer Architektur und des Tech-Stacks ist getroffen

AC:
- Übersicht der für uns relevanten Hostingmöglichkeiten ist erstellt
- folgende Aspekte sind berücksichtigt:
→ Kompatibilität 
→ Preis für 1 Jahr (monatliche Kosten sollten nicht über ca. 6 € sein)
→  versteckte Kosten
→ automatisierte Deployments möglich (ja/nein)
- gemeinsame Entscheidung ist getroffen und im Docs Repository dokumentiert

**Comment by jvoigt** [comment]
Hier witziger weise ein längerer thread mit vielen Vorschlägen vor allem so "edge-runner/static"... Aber nicht alle sind für uns gangbare, aber viele der.Vorschläge könnte man sich noch mal an gucken. (Uberspace ist unter den Vorschlägen)
https://front-end.social/@heydon/112262655128744212

**Comment by jvoigt** [comment]
vielleicht können wir da mal einen kleinen preis-leistungsvergleich aufstellen. Am ende hast du da schon mehr ahnung und ich finde es auch wichtig, dass wir tools nutzen auf die wir auch bock haben.

Wichtig wäre mir persönlich, dass es relativ wartungsarm ist. also ich vermute mal das in 1-2 Jahren wir nicht mehr soviele leute sind und dann muss das totzdem schnell betreut werden können – ich vermute mal das dann tendenziell bei mir hängen bleibt :P
Ansonsten finde ich es auch cool auf "partner/hoster/services" auch ohne "BigTech" und tracking und privacy und vielleicht auch einen etwas politischem anspruch zusetzen, aber nur wenn es kein extra aufwand ist (deswegen gitthub) aber wo es nicht nötig ist....

Mir würden jetzt noch drei optionen einfallen: vielleicht habt ihr das schon geprüft und dann bitte ignorieren.

- wir nutzen eine reine Docker-Hoster. also sowas wie AWS Fargate (nur vielleicht) nicht bei AWS, mir fällt gerade nicht ein wie die anderen hießen.

- wir nutzen so einen magic CDN/edge hoster wie vercel oder cloudflare siehe z.b https://docs.astro.build/en/guides/deploy/

- shared webhoster wie uberspace https://manual.uberspace.de/billing-general/

Wenn man ganz tief ins rabbithole möchte könnten man bei irgenwelche kollektiven fragen, z.b. https://www.systemli.org/service/hosting/

**Comment by LaurinStreng** [comment]
Die Entscheidung vom Hosting hat sich geklärt wir versuch alles über github Pages abzubilden. Da das die günstige Lösung ist
