### ISSUE TITLE
CI/CD aufsetzen 

### ISSUE THREAD

**Issue by jvoigt** [bringbackourneighbours/bringbackourneighbours#42]
Voraussetzung:
- Hostingentscheidung ist getroffen

AKs:
- Grundlegene Konfiguration der Hostinglösung ist eingerichtet
- automatisierte Deployments sind mittels GitHub-Actions möglich

**Comment by LaurinStreng** [comment]
Hostingentscheidung ist getroffen. (Github Pages)

**Comment by LaurinStreng** [comment]
Hier können wir jetzt noch das Test Deployment abbilden.

**Comment by jvoigt** [comment]
hmm also aktuell gibt es sowieo so kein wirkliches review... das heißt dann können wir uns eine dev instanz auch sparen: also deploy to prod und yolo :P

**Comment by jvoigt** [comment]
also ich könnte mir vorstellen das hier erstmal als done zu betrachten
