### ISSUE TITLE
Address--Componente features

### ISSUE THREAD

**Issue by jvoigt** [bringbackourneighbours/bringbackourneighbours#80]
currently the address component ist jkust a placehoölder implementation: it looks a little weird and does not support all properties of an adress.
![image](https://github.com/bringbackourneighbours/bringbackourneighbours/assets/10059188/ac2e4cf8-4a03-4048-a7d7-fc04ef48878b)

Goals:
features we might need:
- whatsApp vs phone
- clickable phone number/whatsapp
- fax for courts
- details/ all info: normaly we only want to show the weburl but not all other information... maybe we can make the address expoandable.
- streetline/zip/city are all option but need to be formatted.
- transliteration of the name of an organisation to other languages.

**Comment by ponychicken** [comment]
Some of this is better now

**Comment by jvoigt** [comment]
abschiebehaftkontaktgruppe has 
instagram: abschiebehaftkg_dresden
facebook: AbschiebehaftkontaktgruppeDD
twitter: KntktGrAHaftDD

**Comment by jvoigt** [comment]
sometimes, detention flyer abschiebehaftkontaktgruppe we only want to show the web url on print?

**Comment by jvoigt** [comment]
also allow for telegram

identifier: deportationalarm
telegram: t.me/deportation_alarm

**Comment by jvoigt** [comment]
also consider: some orgs have multlple phones or mails

**Comment by jvoigt** [comment]
Adressen auf Website auch als Akkordeon
