### ISSUE TITLE
Contentype: Formblanks

### ISSUE THREAD

**Issue by jvoigt** [bringbackourneighbours/bringbackourneighbours#82]
#Wir haben Druckvorlagen zusammengestellt, die im Notfall, also im Falle einer laufenden Abschiebung genutzt werden können. Wir raten aber zu Anträgen und Vollmachten, die von Anwält*innen oder Beratungsstellen, bezogen auf den speziellen Einzelfall, erstellt werden.

Diese Formualrvorlagen gibt es nur auf deutsch... aber die erkläruingen dazu könnte man schon übersetzen.
>> C: ist auf englisch übersetzt

Das war bisher so umgesetzt: https://bringbackourneighbours.de/de/infomaterial/vorlagen-zum-ausdrucken/

Unklar ist noch wie genau diese Formular jetzt im Koffer verknüpft werden.
>> C: Online: Interne Verlinkungen; Ausgedruckt: Als Anhang ganz am Ende.

Zum einen braucht es sicher Shortlinks auf die einzelen Dokumente und zum anderen dies auch irgendwie einzeln.
praktisch bestehen die Formular aus dem Formular selbst (das sind fertige PDFs/Word) aber man könnte die ja auch generieren...
Dazu gibt es aber schon noch erklärtexte die beschreiben was das für ein dokument ist.

>> C: Am besten immer nur interner Link (egal welche Vorlage gemeint ist) auf die Seite, bei die Hinweise und die Vorlagen erklärt werden. Diese Seite wird dann in alle Sprachen übersetzt.

**Comment by jvoigt** [comment]
das ist auf jednefall erstmal low prio!

Generell ist es nicht ratsam, wenn diese vorlagen ohne expertinnen fürs recht ausgefüllt werden, es besteht die gefahr von missverständnissen, auch mit übersetzung. Wie wir das sinnvoll machen müssen wir noch mal sehen. Wir gehne erstmal davon aus, dass wer das rechtlich ausreichend gut kennt, auch mit dem deutsch klar kommt.

**Comment by jvoigt** [comment]
die prio ist dann doch höher: wir müssen das in den flyern verlinken
link/form_detention.yml inabschiebehaft

**Comment by ChriRie2103** [comment]
Asylfolgeantrag als worddokument anlegen, nicht als pdf

**Comment by jvoigt** [comment]
![image](https://github.com/user-attachments/assets/abf5694c-a8b5-4ad6-800b-26acf9c2d8ac)

Mein Layout-Vorschlag für die Seite "Vorlagen zum Ausdrucken". In dem Text am Anfang "dringend" einfügen, also: "Wir raten aber dringend zu Anträgen..." Neben dem Titel der 4 Vorlagen oder unter dem Erklärungstext der 4 Vorlagen einen Icon, so gestaltet wie "Teilen" / "Text kopieren" mit dem Druck-Symbol - alles in unserem blau.

**Comment by ChriRie2103** [comment]
Hinweise auf englisch übersetzt und auf github angelegt

**Comment by ChriRie2103** [comment]
Alle Vorlagen sind jetzt einzeln als pds bzw. bei Asylfolgeantrag als odt auf der Cloud >> alle Vorlagen und Hinweise sind aktualisiert und ready auf der Cloud >> Update 2024 >> 3_Vorlagen zum Ausdrucken

**Comment by jvoigt** [comment]
umsetzung war jetzt erstmal einfach moglich ohne einen neuen Content-Type:

die Seite ist eine "page" und die Dokumente werden in `/public/forms` hochgeladen. Von da kann man sie als normalen (externen Link runter laden.
